### ISSUE TITLE
摘要無法從第五行開始

### ISSUE THREAD

**Issue by geant44** [liao961120/ntuthesis#10]
您好我遇到一個問題就是摘要無法從第五行開始
![image](https://user-images.githubusercontent.com/32418208/71777205-a9b66b00-2fd7-11ea-91a3-d4540efb048d.png)

**Comment by liao961120** [comment]
抱歉，那是舊的文字。
第一行的那些文字其實就是你寫摘要的地方
```
摘要**第 5 行**開始而且不能是空行。摘要**第 5 行**開始而且不能是空行。摘要**第 5 行**開始而且不能是空行。摘要**第 5 行**開始而且不能是空行。
```

**Comment by geant44** [comment]
好喔謝謝

Yongfu Liao <notifications@github.com> 於 2020年1月5日 週日 下午8:28寫道：

**Comment by geant44** [comment]
#11 那我開這個PULL

**Comment by geant44** [comment]
您好我發現摘要會額外產生空白頁

**Comment by liao961120** [comment]
我輸出是正常的 ([ntu-bookdown.pdf](https://github.com/liao961120/ntuthesis/files/4039227/ntu-bookdown.pdf))
你有更改 `index.Rmd` yaml header 裡的 `two-side` 嗎？
```yaml
two-side: false  # Whether to start new chapter on odd pages
```

**Comment by geant44** [comment]
解決了，謝謝。 不過他之前的值為no

Yongfu Liao <notifications@github.com> 於 2020年1月9日 週四 下午3:50寫道：
