### ISSUE TITLE
口試委員審定書不需要頁碼

### ISSUE THREAD

**Issue by geant44** [liao961120/ntuthesis#12]
您好
我需要口試委員審定書關閉頁碼，請問我要怎麼做

**Comment by liao961120** [comment]
你可以使用學校提供的口試委員審定書 (應該沒有頁碼？)
之後再用 PDF 軟體插入那頁口試委員審定書

如果要關閉目錄那邊的頁碼，會有點麻煩，需要修改 LaTeX

**Comment by geant44** [comment]
您好
學校需要關閉目錄那邊的頁碼  ><

Yongfu Liao <notifications@github.com> 於 2020年1月8日 週三 下午3:25寫道：

**Comment by liao961120** [comment]
你可以將 [`latex/template.tex`](https://github.com/liao961120/ntuthesis/blob/a89f5e29f3a5779554a728027f2412c6fba2c5e2/example-thesis/latex/template.tex#L301-L308) 中 301-308 行改成下方程式碼

```tex
\includepdf[pages={1}, scale=1]{front_matter/front_matter.pdf}

\clearpage
\pagenumbering{roman}

\phantomsection
%\addcontentsline{toc}{chapter}{口試委員會審定書}
\pagenumbering{gobble}
\includepdf[pages={1}, scale=1]{certification-scan.pdf}
\pagenumbering{roman}
```

**Comment by geant44** [comment]
請問可以改誌謝的頁碼

Yongfu Liao <notifications@github.com> 於 2020年1月9日 週四 上午10:09寫道：

**Comment by liao961120** [comment]
你可以在 [L313](https://github.com/liao961120/ntuthesis/blob/a89f5e29f3a5779554a728027f2412c6fba2c5e2/example-thesis/latex/template.tex#L313-L314) 之前插入 `setcounter{page}{1}` 看看 (我沒試過)
```latex
\setcounter{page}{1}
\chapter*{$acknowledgements-title$}
$acknowledgements$
```

**Comment by geant44** [comment]
您好成功了
\pagenumbering{roman}

$if(acknowledgements)$
\phantomsection
\chapter*{$acknowledgements-title$}
$acknowledgements$
\setcounter{page}{3}
\addcontentsline{toc}{chapter}{$acknowledgements-title$}
$endif$

Yongfu Liao <notifications@github.com> 於 2020年1月9日 週四 下午5:52寫道：
