### ISSUE TITLE
TimesNewRoman無法下載

### ISSUE THREAD

**Issue by geant44** [liao961120/ntuthesis#14]
您好
   ntuthesis::download_fonts()下載TimesNewRoman有問題
`
嘗試 URL 'https://depend.netlify.com/fonts/TimesNewRoman.zip'
Error in utils::download.file(enfont, destfile = temp_enfont) : 
  無法開啟 URL 'https://depend.netlify.com/fonts/TimesNewRoman.zip'
此外: Warning message:
In utils::download.file(enfont, destfile = temp_enfont) :
  cannot open URL 'https://depend.netlify.com/fonts/TimesNewRoman.zip': HTTP status was '404 Not Found'
`

**Comment by liao961120** [comment]
現在應該可以了～

**Comment by geant44** [comment]
您好現在正常了，謝謝

Yongfu Liao <notifications@github.com> 於 2020年2月18日 週二 下午1:02寫道：
