### ISSUE TITLE
非常感謝!廖大神~有些問題要請教

### ISSUE THREAD

**Issue by ChenChingChih** [liao961120/ntuthesis#15]
在project_name內的  

- 01-install-compile.rmd檔 28~34行，我執行後會出現無法匯入rmd-template，即便figs資料夾內有這兩個檔案。
`
```{r fig.cap="透過 RStudio 匯入論文模板"}
if (knitr::is_html_output()) {
  knitr::include_graphics("figs/rmd-template.gif")
} else {
  knitr::include_graphics("figs/rmd-template.png")
}
```
`

- 生成gitbook時，在_output.yml 5\~6行所會用到的檔案latex/custom.js、和disqus.html都不存在。
`
  includes:
    in_header: latex/custom.js
    after_body: disqus.html
`
使用後的小建議 : 
可以在project_name內直接內建R-project檔，因為在[使用說明2](https://yongfu.name/ntuthesis/doc/export-thesis.html)中，"將該資料夾變更為 bookdown 專案"，在操作時並不太順利~  
再次感謝\~在生成pdf與html後莫名的感動~

**Comment by liao961120** [comment]
我剛更新模板內容了
你可以重新下載套件再試看看

可以直接建立 `.Rproj`，你可以用文字編輯器在裡面放入這些內容：
```
Version: 1.0

RestoreWorkspace: Default
SaveWorkspace: Default
AlwaysSaveHistory: Default

EnableCodeIndexing: Yes
UseSpacesForTab: Yes
NumSpacesForTab: 4
Encoding: UTF-8

RnwWeave: Sweave
LaTeX: XeLaTeX

BuildType: Website
```

**Comment by ChenChingChih** [comment]
感謝!
但[使用說明](https://yongfu.name/ntuthesis/doc/)連結跑掉了!

**Comment by liao961120** [comment]
可以先到 https://doc-ntuthesis.netlify.com/ 閱讀文件
