### ISSUE TITLE
front-matter如何修改校名

### ISSUE THREAD

**Issue by ChenChingChih** [liao961120/ntuthesis#18]
作者你好，想請問如何修改front-matter中論文封面、口試委員審定書中的校名呢?我在`_person-info.yml`中沒有找到對應的欄位
感謝!

**Comment by liao961120** [comment]
模板無法修改口試委員審定書校名
不過既然審定書本來就要簽名後掃描
何不直接使用你們學校提供的，再轉換成 pdf 檔？

**Comment by ChenChingChih** [comment]
嗯嗯！口試委員的部分，我直接使用學校提供的檔案來轉PDF檔
那想請教論文封面的校名是否也無法從檔案內設定呢？處理的方式就一樣是用PDF的方式加到front-matter中

**Comment by liao961120** [comment]
或許你可以試試修改 [front_matter/ntuvars.tex](https://github.com/liao961120/ntuthesis/blob/d51e8e99ea3f4308bc4b790746d9dd73fabfdb93/example-thesis/front_matter/ntuvars.tex#L11) 裡面的校名 `\university{National Taiwan University}{國立臺灣大學}`

其他的部份應該是在 [`_person-info.yml`](https://github.com/liao961120/ntuthesis/blob/master/example-thesis/_person-info.yml) 裡面設定的，所以不須更動

**Comment by ChenChingChih** [comment]
感謝!不過還是無法調整...我改用學校給的版型，再以pdf方式作為封面!
