### ISSUE TITLE
頁碼問題：將所有頁碼移至頁面底端？

### ISSUE THREAD

**Issue by geant44** [liao961120/ntuthesis#6]
請問一下我想ntuthesis內文頁碼調到下面

**Comment by geant44** [comment]
是的

**Comment by liao961120** [comment]
模板中的 `latex/preamble-zh.tex` 與 `latex/preamble-en.tex` 已新增選項能讓輸出論文的頁碼至於頁面底端中央。

在上述的兩個檔案中找到這兩行，取消註解 (移掉開頭的 `%`) 即可達成：
```tex
%\usepackage{fancyhdr}
%\pagestyle{fancy}
```

**Comment by geant44** [comment]
好的，謝謝您
