### ISSUE TITLE
無法輸出pdf

### ISSUE THREAD

**Issue by geant44** [liao961120/ntuthesis#7]
目前遇到一個問題，是第一頁的r輸出無法只顯示結果。會顯示錯誤
`!LaTeX Error: Environment Shaded undefined.`

**Comment by liao961120** [comment]
第一頁是指什麼(front-matter還是內文)?無法只顯示結果是什麼意思?
是 \usepackage{fancyhdr} 加入之後才造成的嗎？

**Comment by liao961120** [comment]
是 `\usepackage{fancyhdr}` 加入之後才造成的嗎？

**Comment by liao961120** [comment]
我這邊無法重現你的問題，你用的版本是最新版嗎？

**Comment by geant44** [comment]
是內文的部份，插入圖片的時候會遇到這個問題，我目前使用最新版。
請問可以輸出更詳細的日誌？

**Comment by liao961120** [comment]
可以將你的整個專案壓縮傳上來嗎？我不知道為何你的會這樣。
「更詳細的日誌」是什麼？

**Comment by geant44** [comment]
rmd可以不包含？  更詳細的日誌是指可以顯示更多的訊息

**Comment by geant44** [comment]
目前發現整個內文需要有一個r的程式碼要顯示程式碼就可以解決

**Comment by liao961120** [comment]
「r的程式碼要顯示程式碼」是指 `echo=TRUE` 嗎？

````markdown
```{r echo=TRUE}
some_r_code <- "..."
```
````

可以把你解決的方法的 **r 的程式碼**以及你的 `preamble.tex` 貼上來給我看嗎？

**Comment by geant44** [comment]
這裡
[Uploading R.tar.gz…]()

**Comment by liao961120** [comment]
沒有上傳成功喔

**Comment by geant44** [comment]
不好意思，成功的方法是只要一個R的程式碼顯示程式碼就能正常
