### ISSUE TITLE
圖號問題

### ISSUE THREAD

**Issue by geant44** [liao961120/ntuthesis#8]
請問內文的圖號可以加入章節的號碼？

**Comment by liao961120** [comment]
內文的圖號是指下圖的「圖 5.1」嗎？

p.s. 希望你在提出問題時可以**說明的更詳細、精確**。例如關於排版，提供附圖會是一個好方法。

![Screenshot from 2019-06-17 23-52-13](https://user-images.githubusercontent.com/32927002/59618560-101e8d80-915b-11e9-88ff-6c0d346c4433.png)

**Comment by geant44** [comment]
好的，不好意思，而且剛剛發現這個部份已經實現了，問題是圖目錄
![2019-06-18 14-15-27 的螢幕擷圖](https://user-images.githubusercontent.com/32418208/59657581-bc9c5600-91d3-11e9-8774-2801fc232f24.png)
